name: CI

on:
  push:
    branches:
      - main  # Change to 'master' if your main branch is named 'master'
  pull_request:
    branches:
      - main  # Change to 'master' if your main branch is named 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify your Python version here

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        cd backend
        # Replace with your test command, e.g., pytest, unittest, etc.
        python -m unittest discover

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify your Node.js version here

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --watchAll=false  # Run tests in CI mode
